

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql   # maps to a local folder on your host

  backend:
    build: ./backend
    container_name: dotnet_api
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=mydb;user=myuser;password=mypassword
    ports:
      - "5000:8080"
    volumes:
      - ./backend:/app
    command: ["dotnet", "watch", "run", "--urls", "http://+:8080"]
 

  frontend:
    build: ./frontend
    container_name: react_ui
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app
      - /app/node_modules             # preserve container's node_modules
volumes:
  db_data:
